services:
  NGINX:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d:ro # nginx 配置
      - ./nginx/logs:/var/log/nginx # nginx 日志
      - /etc/localtime:/etc/localtime
    networks:
      - net-app
  PHP:
    image: suyar/php:8.2-fpm
    #image: php:8.2-cli
    container_name: app-php
    ports:
     - 9082:9000
    volumes:
      - ./www:/var/www/html:rw
      - /etc/localtime:/etc/localtime
    depends_on:
     - REDIS
     - MYSQL
    networks:
     - net-app
  MYSQL:
    image: mysql:latest
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      #- ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    ports:
     - 3308:3306     
    networks:
      - net-app
  REDIS:
    image: redis:latest
    container_name: app-redis
    ports:
     - 6378:6379 
    networks:
      - net-app
    volumes:
      - ./redis/data:/data
networks:
  net-app:
    driver: bridge